local colors_8 = {
	Color3.fromRGB(0, 0, 0),
	Color3.fromRGB(187, 0, 0),
	Color3.fromRGB(0, 187, 0),
	Color3.fromRGB(187, 187, 0),
	Color3.fromRGB(0, 0, 187),
	Color3.fromRGB(187, 0, 187),
	Color3.fromRGB(0, 187, 187),
	Color3.fromRGB(187, 187, 187),

	-- bright colors
	Color3.fromRGB(85, 85, 85),
	Color3.fromRGB(255, 85, 85),
	Color3.fromRGB(85, 255, 85),
	Color3.fromRGB(255, 255, 85),
	Color3.fromRGB(85, 85, 255),
	Color3.fromRGB(255, 85, 255),
	Color3.fromRGB(85, 255, 255),
	Color3.fromRGB(255, 255, 255),
}

return { Colors8 = colors_8 }
